services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000  # Default UID for syncthing user in the official image
      - PGID=1000  # Default GID for syncthing user in the official image
      - TZ=Europe/Amsterdam # Adjust your timezone if needed
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - "8384:8384"   # Syncthing Web GUI
      - "22000:22000" # Syncthing TCP
      - "22000:22000/udp" # Syncthing UDP
      - "21027:21027/udp" # Syncthing Discovery
    restart: unless-stopped
